---
- name: Setup PC
  hosts: mypc
  vars:
    wifi_iface: wlp0s20f3
    ethernet_iface: enp0s31f6

  pre_tasks:
    - fail:
        msg: Set wifi_iface variables in playbook and rerun.
      when:
        - (wifi_iface is not defined) or (wifi_iface|length == 0)
      tags: ["i3_config","setup_wifi"]

    - fail:
        msg: Set ethernet_iface variables in playbook and rerun.
      when:
        - (ethernet_iface is not defined) or (ethernet_iface|length == 0)
      tags: ["i3_config","setup_wifi"]

    - set_fact:
        home_dir: "/home/{{ ansible_user }}"
      tags: always

    - name: Create User home bin
      file:
        dest: "{{ home_dir }}/bin"
        state: directory
      tags: always

    - name: Add user home bin dir to system-wide $PATH.
      copy:
        dest: /etc/profile.d/custom-path.sh
        content: 'PATH=$PATH:{{ home_dir }}/bin'
      become: true
      tags: always

  tasks:
    - name: Update the apt package index
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      tags: always

    - name: Install packages
      apt:
        pkg:
          - ansible
          - sudo
          - vim
          - xorg
          - xorg-dev
          - arandr
          - pcmanfm
          - wpasupplicant
          - i3
          - i3blocks
          - slim
          - rofi
          - xfce4-terminal
          - feh
          - xcompmgr
          - xclip
          - xsel
          - xinput
          - pulseaudio-utils
          - graphicsmagick-imagemagick-compat
          - qalc
          - openconnect
          - htop
          - gcc
          - make
          - pm-utils
          - jq
          - pavucontrol
          - lm-sensors
          - fonts-font-awesome
      become: true
      tags: always

    - name: Setup feh-rand
      copy:
        dest: "{{ home_dir }}/bin/feh-rand"
        mode: "0755"
        content: |
          #!/bin/bash

          dst="$HOME/Pictures/backgrounds"
          url='https://source.unsplash.com/1600x900'
          proxy=$PERSONAL_PROXY
          filename=$(date +"%Y%m%d_%H%M%S.jpg")
          
          export DISPLAY=":0.0"
          mkdir -p $dst
          curl -sL -x $proxy $url -o $dst/$filename
          convert $dst/$filename $dst/$(basename -s '.jpg' $filename).png
          feh --bg-fill  $dst/$filename
          find $dst -mtime +1 -exec rm -vf {} \;

    - name: Cron for feh-rand
      cron:
        special_time: "hourly"
        job: "{{ home_dir }}/bin/feh-rand"

    #### Install brave
    - name: Get keyring file
      get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
      become: true
      tags: install_brave
    
    - name: Add Brave repository to list of repositories
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
        state: present
      become: true
      tags: install_brave

    - name: Update apt cache
      apt: update_cache=yes
      become: true
      tags: install_brave
    
    - name: Install Brave
      apt:
        name: brave-browser
        state: present
      become: true
      tags: install_brave

    ####
    - name: Install Clipmenu
      copy:
        src: "{{ item }}"
        dest: "/usr/bin"
        mode: "0755"
      with_items:
        - files/clipmenu/clipctl
        - files/clipmenu/clipdel
        - files/clipmenu/clipmenu
        - files/clipmenu/clipmenud
      become: true
      tags: install_clipmenu

    - name: Create systemd file
      copy:
        src: files/clipmenu/clipmenud.service
        dest: /usr/lib/systemd/system/clipmenud.service
      notify: start clipmenud
      become: true
      tags: install_clipmenu
      
    - name: enable clipmenud service
      systemd:
        name: clipmenud
        daemon_reload: yes
        state: started
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}"
      tags: install_clipmenu

    - name: Get clipnotify
      git:
        repo: https://github.com/cdown/clipnotify
        dest: /tmp/clipnotify
      tags: install_clipmenu

    - name: Build clipnotify
      shell:
        cmd: make
        chdir: /tmp/clipnotify
      tags: install_clipmenu

    - name: Install clipnotify
      shell:
        cmd: cp ./clipnotify /usr/bin
        chdir: /tmp/clipnotify
      become: true
      tags: install_clipmenu

    ####
    - name: Copy i3 config
      copy:
        src: files/config/i3.conf
        dest: "{{ home_dir }}/.config/i3/config"
      notify: restart i3
      tags: i3_config

    - name: Copy i3blocks tools
      copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}/.config/i3/"
        mode: "0755"
      with_items:
        - ./files/i3blocks/
      notify: restart i3
      tags: i3_config

    - name: Apply i3blocks config
      template:
        src: files/config/i3blocks.conf.j2
        dest: "{{ home_dir }}/.config/i3/i3blocks.conf"
      notify: restart i3
      tags: i3_config

    ####
    - name: Set Xresources config
      copy:
        dest: "{{ home_dir }}/.Xresources"
        content: |
          Xft.autohint: 0
          Xft.antialias: 1
          Xft.hinting: true
          Xft.hintstyle: hintslight
          Xft.dpi: 96
          Xft.rgba: rgb
          Xft.lcdfilter: lcddefault
      notify: restart i3
      tags: i3_config

    ####
    - name: Install sp spotify controller
      get_url:
        url: https://gist.githubusercontent.com/streetturtle/fa6258f3ff7b17747ee3/raw/e52c3ed7086461a4e218e3121949e4515c5ccc78/sp
        dest: "{{ home_dir }}/bin/sp"
        mode: "0755"

    ####
    - name: Setup Wifi auto start config
      copy:
        dest: /etc/network/interfaces.d/{{ wifi_iface }}.conf
        content: |
          auto {{ wifi_iface }}
          iface {{ wifi_iface }} inet dhcp
                  wpa-conf {{ home_dir }}/.wpa_supplicant.conf
      become: true
      tags: setup_wifi

    ####
    - name: Setup touchpad tap and Natural Scrolling
      copy:
        dest: {{ home_dir }}/.xsessionrc
        content: |
          # run "xinput list" to find touchpad device name and
          # "xinput list-props '<touchpad device name>'" to list its properties
          xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
          xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1

# setup backlight
# https://gitlab.com/wavexx/acpilight/-/tree/master
###

  handlers:
    - name: restart i3
      shell: bash -c "i3-msg -t command restart -s $(ls $XDG_RUNTIME_DIR/i3/ipc-socket.*)"
      args:
        executable: /bin/bash

    - name: start clipmenud
      systemd:
        name: clipmenud
        state: started
      become: true
