#!/bin/bash

COLOR_GE80=${COLOR_GE80:-#00FF00}
COLOR_GE60=${COLOR_GE60:-#FFF600}
COLOR_GE40=${COLOR_GE40:-#FFAE00}
COLOR_LOWR=${COLOR_LOWR:-#FF0000}
COLOR_DOWN=${COLOR_DOWN:-#FF0000}

#------------------------------------------------------------------------

INTERFACE="${INTERFACE:-wlan0}"

#------------------------------------------------------------------------

ESSID=$(/sbin/iwconfig $INTERFACE | perl -n -e'/ESSID:"(.*?)"/ && print $1')

#------------------------------------------------------------------------

QUALITY=$(/sbin/iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

#------------------------------------------------------------------------

state () {
  cat /sys/class/net/$INTERFACE/operstate
}

ipv4 () {
  ip addr show $INTERFACE | awk 'BEGIN{ORS=","} /inet / {print $2}' | sed 's/,$//g'
}

ipv6 () {
  ip -6 addr show $INTERFACE | perl -n -e '/inet6 ([^\/]+)/ && print $1'
}

if [ "$(state)" != 'up' ]; then
  echo down # full text
  echo down # short text
  echo \#FF0000 # color
  exit 0
fi

# TODO eventually accept a -4 or -6 flag to force only one or the other
IPADDR=$(ipv4)

if [ -z "$IPADDR" ]; then
  echo no addr # full text
  echo no addr # short text
  exit 0
fi

# full text
echo "$ESSID ($QUALITY%) $IPADDR"

# short text
echo "$ESSID ($QUALITY%) $IPADDR"

# color
if [[ $QUALITY -ge 80 ]]; then
    echo $COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    echo $COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    echo $COLOR_GE40
else
    echo $COLOR_LOWR
fi
